# **NUMPY**
* Used for Mathematical Calculations on data set.
* Type of list which is faster as they are stored at one particular place.
* High Performance
* Array stored values of similar data type
* Indexing and slicing is possible in Arrays

TO import Numpy

`!pip install Numpy`

pip --- python installation package



In [ ]:
!pip install Numpy

In [ ]:
import numpy as np

In [ ]:
lst = [1,2,3,4,5]
print(type(lst))
print(lst)

<class 'list'>
[1, 2, 3, 4, 5]


In [ ]:
arr = np.array(lst)
print(type(arr))
print(arr)
print(arr.size)

<class 'numpy.ndarray'>
[1 2 3 4 5]
5


In [ ]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### **One Dimensional Array**

In [ ]:
a = np.array([1,2,3,4])
print(a.ndim) #t know dimesion
print(a.shape)

1
(4,)


### **Two Dimensional Array**

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
2
(4, 3)
12


In [ ]:
#reshape
b = b.reshape(6,2)
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]
 [2 3]]
2
(6, 2)
12


### **Three Dimensional Array**

In [ ]:
c = b.reshape(3,2,2)
print(c)
print(c.ndim)
print(c.shape)
print(c.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 1]
  [2 3]]]
3
(3, 2, 2)
12


In [ ]:
d = c.reshape( 3,4)
print(d)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


### **Indexing**

In [ ]:
#1d-Array
arr = np.array([1,2,3,4])
print(arr[2])
sum = 0
for i in arr:
  sum += i
print(sum)
print(arr[2:])

3
10
[3 4]


In [ ]:
#2d-array
a = np.array([[1,2,3,4],[9,8,7,6]])
print(a)
print(a[1,2])
print(a[1][2:])

[[1 2 3 4]
 [9 8 7 6]]
7
[7 6]


In [ ]:
#linspace(start,end,no of values b/w)
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#indentity matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#random
arr = np.random.randint(0,10,20)
arr

array([2, 9, 5, 4, 2, 1, 7, 1, 3, 7, 7, 7, 5, 4, 5, 0, 6, 5, 2, 0])

In [ ]:
arr = np.random.rand(3,3)
print(arr)
print(arr.max())
print(arr.argmax())
print(arr.min())

print(arr.argmin())

[[0.75651079 0.32865164 0.00603065]
 [0.40063673 0.92954718 0.289735  ]
 [0.58029859 0.59569419 0.56698275]]
0.92954718107517
4
0.006030651619176708
2


In [ ]:
#arange -> a range of values within a specific limit with a space value
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### **Slicing**

In [ ]:
#1d
a = np.arange(0,10,2)
print(a)
print(a[0:])
print(a[-a.size:])

[0 2 4 6 8]
[0 2 4 6 8]
[0 2 4 6 8]


In [ ]:
#2d
a = np.linspace(0,24,9)
a = a.reshape(3,3)
print(a)
print(a[0:1,1:3])
print(a[2:3,0:2])

[[ 0.  3.  6.]
 [ 9. 12. 15.]
 [18. 21. 24.]]
[[3. 6.]]
[[18. 21.]]


In [ ]:
#Mathematical Operations
a = np.arange(0,10,2)
b = a.copy() #copy func copies the data from given array
d = a.view() #view func refletes the changes which done to 'a' also
c = a+b
print(c)
print(np.sqrt(c))
print(np.sin(c))

[ 0  4  8 12 16]
[0.         2.         2.82842712 3.46410162 4.        ]
[ 0.         -0.7568025   0.98935825 -0.53657292 -0.28790332]


In [ ]:
# create 5d array which contains from 0-24
a = np.arange(0,25,1)
print(a)
b = a.reshape(5,5)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]







# **PANDAS**

*   Data Analytics similar to Exel
*   Series -> 1d array conatins array of data with indexing and we can change the indexing aslo.
*   DataFrame -> rows and columns

Importing pandas
```
 !pip install pandas
```





In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

1.5.3


### **Series**

In [ ]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [ ]:
#convert list to pandas series
ser = pd.Series(lst)
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
label = ['a','b','c','d','e']
ser1 = pd.Series(lst,index=label)
ser1

a    1
b    2
c    3
d    4
e    5
dtype: int64

*Difference between series and numpy arrays*
*   *if no of rows > 500k then series is prefered*
*   *if<500k then numpy arrays used*



In [ ]:
#Series from Dctionary
Marks = {"Maths":98,"Physics":90,"Chemistry":89,"Social":83}
ser2 = pd.Series(Marks)
ser2

Maths        98
Physics      90
Chemistry    89
Social       83
dtype: int64

In [ ]:
ser3 = pd.Series(Marks,index=["Maths","Physics"])
ser3

Maths      98
Physics    90
dtype: int64

In [ ]:
#Accessing elemets of series / Indexing in Series
print(ser3["Maths"])
print(ser3[0])

98
98


In [ ]:
#Slicing
print(ser2[1:3])
print(ser2[-3:-1])

Physics      90
Chemistry    89
dtype: int64
Physics      90
Chemistry    89
dtype: int64


In [ ]:
print(ser2.shape)
print(type(ser2))

(4,)
<class 'pandas.core.series.Series'>


### **Data Frame**

In [ ]:
#DataFrame using list
lst = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
col = ['a','b','c','d']
df = pd.DataFrame(lst,index=['A','B','C'],columns=col)
df

a   b   c   d
A  1   2   3   4
B  5   6   7   8
C  9  10  11  12

In [ ]:
#DataFrame using Dictionary
dict = {"Name":["Netaji","Prathyusha","Venkatesh"],"Age":[19,18,20],"Branch":['CSE','CSE-AI&ML',"ECE"]}
df2 = pd.DataFrame(dict)
df2

Name  Age     Branch
0      Netaji   19        CSE
1  Prathyusha   18  CSE-AI&ML
2   Venkatesh   20        ECE

In [ ]:
print(type(df2))
print(df2.shape)
print(df2.columns)

<class 'pandas.core.frame.DataFrame'>
(3, 3)
Index(['Name', 'Age', 'Branch'], dtype='object')


In [ ]:
#Rename : Columns
df2.rename(columns={"Name":"St-name"})

St-name  Age     Branch
0      Netaji   19        CSE
1  Prathyusha   18  CSE-AI&ML
2   Venkatesh   20        ECE

In [ ]:
print(df2.columns)
print(df2.columns.values)
print(df2.columns.values[0:2],"\n")
df2.columns.values[1]="St-Age" #Other way to rename
df2

Index(['Name', 'Age', 'Branch'], dtype='object')
['Name' 'Age' 'Branch']
['Name' 'Age'] 



Name  St-Age     Branch
0      Netaji      19        CSE
1  Prathyusha      18  CSE-AI&ML
2   Venkatesh      20        ECE

In [ ]:
#Drop Columns -> it will not change the original df2
df2.drop("Age",axis=1)

Name     Branch
0      Netaji        CSE
1  Prathyusha  CSE-AI&ML
2   Venkatesh        ECE

In [ ]:
#Drop from original
df2["Age"]=[19,18,20]
df2["Name"] = ["Netaji","Prathyusha","Venky"]
df2["Place"]=["SKLM","NLR","VZM"]
df2.drop("Name",axis=1,inplace=True)
print(df2)

   St-Age     Branch Place
0      19        CSE  SKLM
1      18  CSE-AI&ML   NLR
2      20        ECE   VZM


In [ ]:
d1 = pd.DataFrame({"Name":["Netaji","Prathyusha","Venkatesh"],"Age":[19,18,20],"Branch":['CSE','CSE-AI&ML',"ECE"]})
d2 = pd.DataFrame({"Name":["A","B","C"],"Age":[19,18,20],"Branch":['CSE','CSE-AI&ML',"ECE"],"Place":["SKLM","NLR","VZM"]})
d1.append(d2)

<ipython-input-42-a5dfd38cc857>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  d1.append(d2)


Name  Age     Branch Place
0      Netaji   19        CSE   NaN
1  Prathyusha   18  CSE-AI&ML   NaN
2   Venkatesh   20        ECE   NaN
0           A   19        CSE  SKLM
1           B   18  CSE-AI&ML   NLR
2           C   20        ECE   VZM

In [ ]:
pd.concat([d1,d2])

Name  Age     Branch Place
0      Netaji   19        CSE   NaN
1  Prathyusha   18  CSE-AI&ML   NaN
2   Venkatesh   20        ECE   NaN
0           A   19        CSE  SKLM
1           B   18  CSE-AI&ML   NLR
2           C   20        ECE   VZM

In [ ]:
# Here indexing is not correct
d3 = d1.append(d2,ignore_index="True")
d3

<ipython-input-44-e11b0e03c99a>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  d3 = d1.append(d2,ignore_index="True")


Name  Age     Branch Place
0      Netaji   19        CSE   NaN
1  Prathyusha   18  CSE-AI&ML   NaN
2   Venkatesh   20        ECE   NaN
3           A   19        CSE  SKLM
4           B   18  CSE-AI&ML   NLR
5           C   20        ECE   VZM

### **Handling NAN Missing Values**


*   Delete row/column
*   imputing values filling with a specific values
*if 70-80% is null in particular column ---- delete column




In [ ]:
import numpy as np
f1 = pd.DataFrame({"Name":["Netaji","Preeti",np.nan,"AAyush","Venky","Phani"],"Age":[np.nan,29,np.nan,19,24,np.nan],"City":["SKLM","NLR",np.nan,np.nan,"BZA","GTR"]})
f1

Name   Age  City
0  Netaji   NaN  SKLM
1  Preeti  29.0   NLR
2     NaN   NaN   NaN
3  AAyush  19.0   NaN
4   Venky  24.0   BZA
5   Phani   NaN   GTR

In [ ]:
f1.isnull()

Name    Age   City
0  False   True  False
1  False  False  False
2   True   True   True
3  False  False   True
4  False  False  False
5  False   True  False

In [ ]:
f1.isnull().any()

Name    True
Age     True
City    True
dtype: bool

In [ ]:
f1.isnull().sum()

Name    1
Age     3
City    2
dtype: int64

In [ ]:
#Deleting the rows conatining null value
#rows = axis=0
#columns = axis=1
f1.dropna(axis=0) #inplace=True if we want to commit

Name   Age City
1  Preeti  29.0  NLR
4   Venky  24.0  BZA

In [ ]:
# imputing with mean,median,mode
m = f1['Age'].mean() #mean
f1['Age'] = f1['Age'].fillna(m)
f1

Name   Age  City
0  Netaji  24.0  SKLM
1  Preeti  29.0   NLR
2     NaN  24.0   NaN
3  AAyush  19.0   NaN
4   Venky  24.0   BZA
5   Phani  24.0   GTR

In [ ]:
f1 = pd.DataFrame({"Name":["Netaji","Preeti",np.nan,"AAyush","Venky","Phani"],"Age":[np.nan,29,np.nan,19,18,np.nan],"City":["SKLM","NLR",np.nan,np.nan,"BZA","BZA"]})
med = f1['Age'].median() #meadian
f1['Age'] = f1['Age'].fillna(med)
f1

Name   Age  City
0  Netaji  19.0  SKLM
1  Preeti  29.0   NLR
2     NaN  19.0   NaN
3  AAyush  19.0   NaN
4   Venky  18.0   BZA
5   Phani  19.0   BZA

In [ ]:
f1 = pd.DataFrame({"Name":["Netaji","Preeti",np.nan,"Phani","Venky","Phani"],"Age":[np.nan,29,21,19,18,np.nan],"City":["SKLM","SKLM",np.nan,np.nan,"BZA","GTR"]})
f1['City']=f1['City'].fillna(f1['City'].mode()[0]) #mode generally stores as series as there can be 2 values have same no of repeats
f1['Name']=f1['Name'].fillna(f1['Name'].mode()[0])
med = f1['Age'].median() #meadian
f1['Age'] = f1['Age'].fillna(med)
f1

Name   Age  City
0  Netaji  20.0  SKLM
1  Preeti  29.0  SKLM
2   Phani  21.0  SKLM
3   Phani  19.0  SKLM
4   Venky  18.0   BZA
5   Phani  20.0   GTR

In [ ]:
f1.City.value_counts()

SKLM    4
BZA     1
GTR     1
Name: City, dtype: int64

In [ ]:
group = f1.groupby("City")
print(group)
print(group.mean())

        Age
City       
BZA   18.00
GTR   20.00
SKLM  22.25


<ipython-input-54-d7025b1b3718>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(group.mean())


In [ ]:
f1

Name   Age  City
0  Netaji  20.0  SKLM
1  Preeti  29.0  SKLM
2   Phani  21.0  SKLM
3   Phani  19.0  SKLM
4   Venky  18.0   BZA
5   Phani  20.0   GTR

In [ ]:
f1.head(2)

Name   Age  City
0  Netaji  20.0  SKLM
1  Preeti  29.0  SKLM

In [ ]:
f1.tail(2)

Name   Age City
4  Venky  18.0  BZA
5  Phani  20.0  GTR

In [ ]:
#Accessing rows and columns
#loc #iloc
f1.loc[2] #it is a pandas.series

Name    Phani
Age      21.0
City     SKLM
Name: 2, dtype: object

In [ ]:
f1.loc[2:]

Name   Age  City
2  Phani  21.0  SKLM
3  Phani  19.0  SKLM
4  Venky  18.0   BZA
5  Phani  20.0   GTR

In [ ]:
f1.iloc[1:]

Name   Age  City
1  Preeti  29.0  SKLM
2   Phani  21.0  SKLM
3   Phani  19.0  SKLM
4   Venky  18.0   BZA
5   Phani  20.0   GTR

In [ ]:
data = {
    "Calories":[400,230,213],
    "Duration":[50,40,45]
}
data

{'Calories': [400, 230, 213], 'Duration': [50, 40, 45]}

In [ ]:
d_f = pd.DataFrame(data,index=['Day-1','Day-2','Day-3'])
d_f

Calories  Duration
Day-1       400        50
Day-2       230        40
Day-3       213        45

In [ ]:
d_f.loc['Day-2']

Calories    230
Duration     40
Name: Day-2, dtype: int64

In [ ]:
#loc  -> takes labelled indexes
#iloc -> takes integer base indexes
d_f.iloc[1]
d_f.iloc[1:3,0:3]

Calories  Duration
Day-2       230        40
Day-3       213        45

In [ ]:
d_f.loc["Day-2":,['Calories']]

Calories
Day-2       230
Day-3       213